---
- hosts: all
  become: true
  tasks:

    - name: Ensure that yum-utils is installed before upgrading packages
      yum:
        name: yum-utils
        state: present

    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest
        update_only: true

    - name: Check if an reboot is required
      command: /usr/bin/needs-restarting -r
      register: reboot_required
      failed_when: reboot_required.rc not in (0,1)

    - name: Reboot system if kernel was updated
      reboot:
      when:
        - reboot_required.rc = 0