---
- hosts: all
  tasks:

  - name: Public Certificate Environment Variable
    debug: msg={{ lookup('env', 'MY_CERT_INI_FILE') }}

  - name: Private Key Environment Variable
    debug: msg={{ lookup('env', 'MY_KEY_INI_FILE') }}

  - name: Public Certificate Extra Variable
    debug: msg={{ winrm_cert }}

  - name: Private Key Extra Variable
    debug: msg={{ winrm_key }}
