---
dependency:
  name: galaxy
driver:
  name: podman
lint: |
  yamllint .
  ansible-lint
platforms:
  - name: instance
    image: docker.io/pycontribs/centos:8
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
